### ISSUE TITLE
Por favor ayuda! 

### ISSUE THREAD

**Issue by stylustonypro** [jonalvarezz/platzi-graphql-fullstack#19]
![image](https://user-images.githubusercontent.com/6721268/155731112-bd05256c-2a59-4c68-85d0-97fd26a94d75.png)

Hola. Profesor puede ayudarme a resolver esto por favor 🙏 .Tengo el mismo error en el curso de GraphQL Apollo y Prisma. Gracias Totales
https://platzi.com/clases/2677-nodejs-graphql/44908-resolvers-para-mutaciones-y-filtros/

**Comment by jonalvarezz** [comment]
Hola Antonio! Muchas gracias por poner esto en mi atención. 

Intentemos solucionarlo aquí y luego copiaré la respuesta en Platzi.

Si dice que la table `main.Avocado` no existe en la base de datos, significa que:
1. Muy probablemente la conexíon a la db funciona
2. pero, la tabla no está.

Podrías intentar correr las migraciones de Prisma en la carpeta api e intentar de nuevo?

```sh
cd api
npx prisma migrate dev
```

**Comment by stylustonypro** [comment]
![image](https://user-images.githubusercontent.com/6721268/155846208-e5d89965-e0e0-44fe-829f-b07c9c916d40.png)
Ahora lo estoy probando en WSL y tengo este error  al ejecutar el comando yarn.

**Comment by jonalvarezz** [comment]
Gracias @stylustonypro, te está pidiendo utilizar la versión 14 de Node.js, cómo instalaste Node.js? Si lo hiciste con algo como `n` o `nvm` es fácil saltar entre versiones.

Si no es el caso, prueba eliminando la entrada `engine` de `package.json`:

A eliminar: 
```
  "engines": {
    "node": "14.x"
  },
```

**Comment by stylustonypro** [comment]
![image](https://user-images.githubusercontent.com/6721268/155864131-93dbe374-b75b-4a6b-abfb-d6961d2e736e.png)
Sigo teniendo el mismo error después de ejecutar 
cd api
npx prisma migrate dev

**Comment by stylustonypro** [comment]
Aquí npx prisma migrate dev 
![image](https://user-images.githubusercontent.com/6721268/156093583-a75bf181-132f-4b13-a636-096e47c4e22b.png)

Y npx prisma studio 
![image](https://user-images.githubusercontent.com/6721268/156093657-08494704-2c6d-4f94-ade0-c5796a29effb.png)

La clase es "Resolvers para mutaciones y filtros"

**Comment by jonalvarezz** [comment]
Antonio, pero que buena noticia! Me alegra mucho que lo hayas encontrado porque, juzgando por las otras capturas de pantallas, todo se ve bien.

Gracias a ti por compartir la solución!

Marcaré el issue como cerrado. :D
